version: '3'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.233.0.0/16

services:
  web:
    restart: unless-stopped
    build: .
    networks:
      - internal
    ports:
      - "5000:5000"

  prometheus:
    depends_on:
      - web # Prometheus needs to be monitoring the web service
    restart: unless-stopped
    image: hub.aiursoft.cn/prom/prometheus
    volumes:
      - prometheus-data:/etc/prometheus
    environment:
      - TZ=UTC
    networks:
      - internal
    ports:
      - "9090:9090"

  grafana:
    depends_on:
      - prometheus # Grafana needs to be using Prometheus as a data source
    restart: unless-stopped
    image: hub.aiursoft.cn/grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - internal
    ports:
      - "3000:3000"
