version: '3'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.233.0.0/16

services:
  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    environment:
      - TZ=UTC
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9090:9090"

  grafana:
    depends_on:
      - prometheus
    restart: unless-stopped
    image: grafana/grafana
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3000:3000"
