version: '3'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.233.0.0/16

services:
  sleepagent:
    restart: unless-stopped
    build: ./src/Anduin.SleepAgent.WebServer
    volumes:
      - sleepagent-data:/data
    networks:
      - internal
    ports:
      - "5000:5000"

  prometheus:
    depends_on:
      - sleepagent # Prometheus needs to be monitoring the web service
    restart: unless-stopped
    build: ./images/prometheus
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus-data:/prometheus
    environment:
      - TZ=UTC
    networks:
      - internal
    ports:
      - "9090:9090"

  grafana:
    depends_on:
      - prometheus # Grafana needs to be using Prometheus as a data source
    restart: unless-stopped
    build: ./images/grafana
    volumes:
      - grafana-config:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - internal
    ports:
      - "3000:3000"

volumes:
  prometheus-config:
  prometheus-data:
  grafana-config:
  grafana-data:
  sleepagent-data: