{
 "title": "ZEPP",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Battery",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Battery{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "HeartRateLast", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pai",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "PaiWeek", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Steps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Steps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Steps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fat Burning",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "FatBurning", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Calorie",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "K calories" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Calorie", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sleep Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "SleepInfoScore", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Meters" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Distance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stands",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Stands", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sleep Time",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "targets": [
    { "expr": "SleepingStatus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sleep Score",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 9, "y": 5 },
   "targets": [
    { "expr": "SleepInfoScore", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "Battery", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    { "expr": "HeartRateLast", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pai",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 10 },
   "targets": [
    { "expr": "PaiWeek", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fat Burning",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 10 },
   "targets": [
    { "expr": "FatBurning", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Calorie",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "targets": [
    { "expr": "Calorie", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Steps",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 16 },
   "targets": [
    { "expr": "rate(Steps[1h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Distance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "meters" } },
   "targets": [
    { "expr": "Steps", "legendFormat": "__auto" }
   ]
  }
 ]
}